# Generated by Django 4.1.3 on 2022-11-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
