# Generated by Django 4.1.3 on 2022-11-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_match_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_number',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
