# Generated by Django 4.1.3 on 2022-11-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_match_match_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_score', models.IntegerField()),
                ('visitor_score', models.IntegerField()),
                ('match_number', models.IntegerField()),
            ],
        ),
    ]
