# Generated by Django 4.1.3 on 2022-11-07 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_realscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realscore',
            name='match_number',
        ),
    ]
