# Generated by Django 4.1.3 on 2022-11-14 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_userscore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
