# Generated by Django 4.1.3 on 2022-12-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_delete_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='points_fg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscore',
            name='points_ko',
            field=models.IntegerField(default=0),
        ),
    ]
