# Generated by Django 4.1.3 on 2022-12-03 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KOMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.TextField()),
                ('local_score', models.IntegerField()),
                ('visitor', models.TextField()),
                ('visitor_score', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('match_number', models.IntegerField()),
                ('round', models.IntegerField()),
                ('qualified', models.IntegerField(default=0)),
            ],
        ),
    ]
