# Generated by Django 4.1.3 on 2022-12-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ko', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='komatch',
            name='looser',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='komatch',
            name='qualified',
            field=models.TextField(default=''),
        ),
    ]
