# Generated by Django 4.1.3 on 2022-12-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ko', '0002_komatch_looser_alter_komatch_qualified'),
    ]

    operations = [
        migrations.AddField(
            model_name='komatch',
            name='punteable',
            field=models.IntegerField(default=1),
        ),
    ]
