# Generated by Django 4.1.3 on 2022-12-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ko', '0003_komatch_punteable'),
    ]

    operations = [
        migrations.CreateModel(
            name='KORealScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.TextField()),
                ('local_score', models.IntegerField()),
                ('visitor_score', models.IntegerField()),
                ('visitor', models.TextField()),
            ],
        ),
    ]
