# Generated by Django 4.1.3 on 2022-12-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ko', '0004_korealscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='korealscore',
            name='looser',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='korealscore',
            name='qualified',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='korealscore',
            name='round',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
